### ISSUE TITLE
Definition of DLLIMPORT function not allowed.

### ISSUE THREAD

**Issue by Alanzote** [yujen/RN4UE4#1]
In my project, I need to compress strings and send them in packets.
However, stringCompressor.h gives me a bunch of errors just for importing it.

`COMPILER ERROR: C2491 - DataStructures::Map<key_type, data_type, key_comparison_func>::SaveLastSearch: definition of dllimport function not allowed.`

I get over 70 errors  in 2 .h files (same errors) the files are: DS_Map.h and DS_OrderedList.h.

**Comment by yujen** [comment]
Thanks for your pull request, Alanzote.
I made some changes in Export.h

**Comment by Alanzote** [comment]
Thanks, it worked now!
